title = "r-ev"
baseURL = "/"
languageCode = "es"
theme = "yajure"
preserveTaxonomyNames = true
enableEmoji = true
# disqusShortname = "r-ev"
#googleAnalytics = "UA-119156756-1"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

# [[menu.main]]
#     name = "reportajes"
#     weight = 20
#     identifier = "reportajes"
#     url = "/reportajes/"

[[menu.main]]
    name = "entrevistas"
    weight = 10
    identifier = "entrevistas"
    url = "/entrevistas/"

# [[menu.main]]
#     name = "portafolios"
#     weight = 40
#     identifier = "portafolios"
#     url = "/portafolios/"

[[menu.main]]
    name = "quorrupto"
    weight = 30
    identifier = "quorrupto"
    url = "/quorrupto/"

[[menu.main]]
    name = "noticias"
    weight = 60
    identifier = "noticias"
    url = "/post/"

# [[menu.main]]
#     name = "comix"
#     weight = 50
#     identifier = "comix"
#     url = "/comix/"

[[menu.main]]
    name = "shop"
    weight = 100
    identifier = "shop"
    url = "https://www.r-evshop.net/"
