title = "r-ev"
baseURL = "/"
languageCode = "en-us"
theme = "cuyagua"
disqusShortname = "r-ev"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
    name = "la r-ev"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "shop"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    url = ""
