title = "r-ev"
baseURL = "/"
languageCode = "en-us"
theme = "cuyagua"
disqusShortname = "r-ev"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
    name = "r-ep"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "r-ep"
    url = "/r-ep/"

[[menu.main]]
    name = "comix"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "comix"
    url = "/comix/"

[[menu.main]]
    name = "melaza"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "melaza"
    url = "/melaza/"

[[menu.main]]
    name = "shop"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    identifier = "shop"
    url = "#"
