title = "r-ev"
baseURL = "/"
languageCode = "es"
theme = "care"
preserveTaxonomyNames = true
enableEmoji = true
SectionPagesMenu = "main"
# disqusShortname = "r-ev"
# googleAnalytics = "UA-119156756-1"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

# [[menu.main]]
#     name = "reportajes"
#     weight = 20
#     identifier = "reportajes"
#     url = "/reportajes/"

# [[params]]
#     DefaultSocialImage = "mydefaultsocialimage.jpg"
#     SiteDescription = "r-ev.net / propaganda underground latinoamericana"
#     Twitter = "lar-ev"

# [[menu.main]]
#     name = "portafolios"
#     weight = 40
#     identifier = "portafolios"
#     url = "/portafolios/"

# [[menu.main]]
#     name = "quorrupto"
#     weight = 30
#     identifier = "quorrupto"
#     url = "/quorrupto/"

# [[menu.main]]
#     name = "Entrevistas"
#     weight = 10
#     identifier = "Entrevistas"
#     url = "/entrevistas/"
#
# [[menu.main]]
#     name = "R-eportajes"
#     weight = 30
#     identifier = "R-eportajes"
#     url = "/r-eportajes/"
#
# [[menu.main]]
#     name = "Portafolios"
#     weight = 20
#     identifier = "Portafolios"
#     url = "/portafolios/"


# [[menu.main]]
#     name = "Noticias"
#     weight = 60
#     identifier = "Noticias"
#     url = "/post/"

# [[menu.main]]
#     name = "comix"
#     weight = 50
#     identifier = "comix"
#     url = "/comix/"

# [[menu.main]]
#     name = "Producto"
#     # weight = 100
#     identifier = "Producto"
#     url = "https://www.r-evshop.net/"
