title = "r-ev"
baseURL = "/"
languageCode = "en-us"
theme = "cuyagua"
disqusShortname = "r-ev"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
    name = "R-eps"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "r-eps"
    url = "/r-eps/"

[[menu.main]]
    name = "Comix"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "comix"
    url = "/comix/"

[[menu.main]]
    name = "Melaza"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "melaza"
    url = "/melaza/"

[[menu.main]]
    name = "shop"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    url = ""
