title = "r-ev"
baseURL = "/"
languageCode = "en-us"
theme = "hugo_r-ev"

[[menu.main]]
    name = "about"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "articulos"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    url = "/article/"
[[menu.main]]
    name = "benko3D"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    url = "/benko3D/"
[[menu.main]]
    name = "archivo"
    #pre = "<i class='fa fa-road'></i>"
    #weight = -100
    url = "/archivo/"
