name = "Cuyagua"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = "0.20"

[author]
  name = "Erik Zitzermann"
  homepage = "erikzitzermann.com"
