name = "Hugo_r-ev"
license = "MIT"
licenselink = "https://github.com/peleco/r-ev/theme/hugo_r-ev/LICENSE.md"
description = "Template for r-ev.net"
homepage = "https://github.com/peleco/r-ev"
tags = ["blog"]
features = ["blog"]
min_version = 0.17

[author]
  name = "Erik Zitzermann"
  homepage = "https://github.com/peleco"
