backend:
  name: github
  repo: peleco/r-ev # Path to your Github repository
  branch: master # Branch to update (master by default)

netlify.configure({'site_id': r-ev.netlify.com});

#publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "news-post" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "post"
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      # - {label: "Categories", name: "categories", widget: "list"}
      #- label: "Image"
      #  name: "imageAttachments"
      #  widget: "list"
        #required: false
      #  fields:
      #    - {label: "Description", name: "description", widget: "string", required: false}
      #    - {label: "Image", name: "image", widget: "image", required: false}
      # - {label: "Categorie", name: "categorie", widget: "string"}

  - name: "r-ep" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "R-ep" # Used in the UI, ie.: "New Post"
    folder: "content/r-ep" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      # - {label: "Color", name: "color", widget: "string"}
      # - {label: "Label", name: "label", widget: "string"}
      #- {label: "Categories", name: "categories", widget: "list"}

  - name: "comix" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "Comix" # Used in the UI, ie.: "New Post"
    folder: "content/comix" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "melaza" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "Melaza" # Used in the UI, ie.: "New Post"
    folder: "content/melaza" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
