backend:
  name: github
  repo: peleco/r-ev # Path to your Github repository
  branch: master # Branch to update (master by default)

netlify.configure({'site_id': r-ev.net});

# publish_mode: editorial_workflow

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

display_url: https://www.r-ev.net

collections: # A list of collections the CMS should be able to edit
  - name: "noticias" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "post"
    label: "Noticias" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      # - {label: "Categories", name: "categories", widget: "list"}
      #- label: "Image"
      #  name: "imageAttachments"
      #  widget: "list"
        #required: false
      #  fields:
      #    - {label: "Description", name: "description", widget: "string", required: false}
      #    - {label: "Image", name: "image", widget: "image", required: false}
      # - {label: "Categorie", name: "categorie", widget: "string"}

  # - name: "reportajes" # Used in routes, ie.: /admin/collections/:slug/edit
  #   type: "article"
  #   label: "Reportajes" # Used in the UI, ie.: "New Post"
  #   folder: "content/reportajes" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
  #   fields: # The fields each document in this collection have
  #     - {label: "Image", name: "image", widget: "image", required: false}
  #     - {label: "Type", name: "type", widget: "hidden", default: "article"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     #- {label: "Description", name: "description", widget: "text"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #     - {label: "Author", name: "author", widget: "string"}
  #     - {label: "Featured", name: "featured", widget: "boolean", default: false}
  #     # - {label: "Color", name: "color", widget: "string"}
  #     # - {label: "Label", name: "label", widget: "string"}
  #     #- {label: "Categories", name: "categories", widget: "list"}

  - name: "entrevistas" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "Entrevistas" # Used in the UI, ie.: "New Post"
    folder: "content/entrevistas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      #- {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "portafolios" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "Portafolios" # Used in the UI, ie.: "New Post"
    folder: "content/portafolios" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      #- {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "r-eportajes" # Used in routes, ie.: /admin/collections/:slug/edit
    type: "article"
    label: "R-eportajes" # Used in the UI, ie.: "New Post"
    folder: "content/r-eportajes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      #- {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "interno" # Used in routes, ie.: /admin/collections/:slug/edit
    # type: "article"
    folder: "content/interno"
    label: "Interno" # Used in the UI, ie.: "New Post"
    # create: true # Allow users to create new documents in this collection
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      # - {label: "Image", name: "image", widget: "image", required: false}
      # - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      #- {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Author", name: "author", widget: "string"}
      # - {label: "Featured", name: "featured", widget: "boolean", default: false}
